import os

settings_mapping = {
    "log_settings": {
        "log_file_path": {
            "default": "./logs/",
            "type": "str",
            "widget": "line_edit",
            "label": "Log File path:",
            "verify_btn": "Verify Log Path",
            "folder_icon": True,
            "verify": "_verify_path_keys",
        },
        "log_file_name": {
            "default": "file.log",
            "type": "str",
            "widget": "line_edit",
            "label": "Log File Name:",
            "verify_btn": "Save Log File Name",
            "verify": "_verify_log_file_name",
        },
        "log_file_max_mbs": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Log File Max Mbs:",
            "verify_btn": "Save Log File Max Mbs",
            "verify": "_verify_no_check_save",
        },
        "log_keep_files_days": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Keep Log File Days:",
            "verify_btn": "Save Log File Days",
            "verify": "_verify_no_check_save",
        },
        "log_backup_count": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Log Backup Count:",
            "verify_btn": "Save Log Backup Count",
            "verify": "_verify_no_check_save",
        },
    },
    "app_settings": {
        "apple_note_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Apple Note Name:",
            "verify_btn": "Verify Apple Note",
            "verify": "_verify_apple_note_name",
        },
        "dictionary_source": {
            "default": "cpod",
            "type": "str",
            "widget": "combo_box",
            "label": "Dictionary Source:",
            "verify_btn": "Save Dictionary Source",
            "combo_box": ["cpod", "mgdb"],
        },
        "auto_save_on_close": {
            "default": True,
            "type": "bool",
            "widget": "combo_box",
            "label": "Auto Save on Close:",
            "verify_btn": "Save Auto Close",
            "combo_box": ["True", "False"],
            "verify": "_verify_no_check_save",
        },
        "google_api_key": {
            "default": "{}",
            "type": "secure",
            "widget": "text_edit",
            "label": "Google Service:",
            "verify_btn": "Verify Google Service",
            "verify": "_verify_google_api_key",
        },
    },
    "anki_settings": {
        "anki_words_deck_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Word's Deck Name:",
            "verify_btn": "Verify Deck",
            "verify": "_verify_anki_deck_name",
        },
        "anki_sents_deck_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Sents's Deck Name:",
            "verify_btn": "Verify Deck",
            "verify": "_verify_anki_deck_name",
        },
        "anki_words_model_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Word's Model Name:",
            "verify_btn": "Verify Model",
            "verify": "_verify_anki_model_name",
        },
        "anki_sents_model_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Sent's Model Name:",
            "verify_btn": "Verify Model",
            "verify": "_verify_anki_model_name",
        },
        "anki_user": {
            "default": "User 1",
            "type": "str",
            "widget": "line_edit",
            "label": "Anki User Name:",
            "verify_btn": "Verify User",
            "verify": "_verify_anki_user_name",
        },
        "anki_audio_path": {
            "default": f"{os.path.expanduser("~")}/Library/Application Support/Anki2/User 1/collection.media",
            "type": "str",
            "widget": "line_edit",
            "label": "Anki Audio path:",
            "verify_btn": "Verify Audio Path",
            "folder_icon": True,
            "verify": "_verify_path_keys",
        },
    },
    "whisper_settings": {
        "whisper_choice": {
            "default": "faster whisper",
            "type": "str",
            "widget": "combo_box",
            "label": "Whisper Source:",
            "verify_btn": "Save Whisper Source",
            "combo_box": ["faster whisper", "whisper"],
        },
        "model": {
            "default": "large",
            "type": "str",
            "widget": "combo_box",
            "label": "Whisper Model:",
            "verify_btn": "Save Whisper Model",
            "combo_box": ["medium", "large", "large-v2", "large-v3"],
        },
        "beam_size": {
            "default": 8,
            "type": "int",
            "widget": "combo_box",
            "label": "Whisper Model:",
            "verify_btn": "Save Beam Size",
            "combo_box": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15],
        },
        "initial_prompt": {
            "default": "Transcribe Mandarin in Simplified Chinese. Transcribe English in Standard English",
            "type": "str",
            "widget": "text_edit",
            "label": "Save Initial Prompt:",
            "verify_btn": "Save Initial Prompt",
        },
    },
}
