import os

settings_mapping = {
    "log_settings": {
        "log_file_path": {
            "default": "./logs/",
            "type": "str",
            "widget": "line_edit",
            "label": "Log File path:",
            "verify_btn": "Verify Log Path",
            "folder_icon": True,
        },
        "log_file_name": {
            "default": "file.log",
            "type": "str",
            "widget": "line_edit",
            "label": "Log File Name:",
            "verify_btn": "Save Log File Name",
        },
        "log_file_max_mbs": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Log File Max Mbs:",
            "verify_btn": "Save Log File Max Mbs",
        },
        "log_keep_files_days": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Keep Log File Days:",
            "verify_btn": "Save Log File Days",
        },
        "log_backup_count": {
            "default": 5,
            "type": "int",
            "widget": "line_edit",
            "label": "Log Backup Count:",
            "verify_btn": "Save Log Backup Count",
        },
    },
    "app_settings": {
        "apple_note_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Apple Note Name:",
            "verify_btn": "Verify Apple Note",
        },
        "anki_words_deck_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Word's Deck Name:",
            "verify_btn": "Verify Deck",
        },
        "anki_sents_deck_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Sents's Deck Name:",
            "verify_btn": "Verify Deck",
        },
        "anki_words_model_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Word's Model Name:",
            "verify_btn": "Verify Model",
        },
        "anki_sents_model_name": {
            "default": "",
            "type": "str",
            "widget": "line_edit",
            "label": "Sent's Model Name:",
            "verify_btn": "Verify Model",
        },
        "anki_user": {
            "default": "User 1",
            "type": "str",
            "widget": "line_edit",
            "label": "Anki User Name:",
            "verify_btn": "Verify User",
        },
        "anki_audio_path": {
            "default": f"{os.path.expanduser("~")}/Library/Application Support/Anki2/User 1/collection.media",
            "type": "str",
            "widget": "line_edit",
            "label": "Anki Audio path:",
            "verify_btn": "Verify Audio Path",
            "folder_icon": True,
        },
        "dictionary_source": {
            "default": "cpod",
            "type": "str",
            "widget": "combo_box",
            "label": "Dictionary Source:",
            "verify_btn": "Save Dictionary Source",
            "combo_box": ["cpod", "mgdb"],
        },
        "auto_save_on_close": {
            "default": True,
            "type": "bool",
            "widget": "combo_box",
            "label": "Auto Save on Close:",
            "verify_btn": "Save Auto Close",
            "combo_box": ["True", "False"],
        },
        "google_api_key": {
            "default": "{}",
            "type": "secure",
            "widget": "text_edit",
            "label": "Google Service:",
            "verify_btn": "Verify Google Service",
        },
    },
}
